---
title: "time -series"
author: "shashikant dewangan"
date: "23 March 2018"
output: html_document
---

# to find the air fair for next 10 years based on my past records
```{r}
plot(AirPassengers)
 # for checking the mean is constant or not we have to calculate it 

# here data is not stationary  so means are increasing and variance are not same
abline(reg = lm(AirPassengers~time(AirPassengers)))
# for checking he trend 

plot(aggregate(AirPassengers,FUN = mean))

data("AirPassengers")
class(AirPassengers)
# telling amount the data is in time series formant or not
start(AirPassengers)
end(AirPassengers)
# this are the star and end of my  time series data 

frequency(AirPassengers)
# this will tell you the cycle of the time series like a series of month
```
```{r}
summary(AirPassengers)

boxplot(AirPassengers~cycle(AirPassengers))
# it will tells us to how the passengers are travelling across the month 

plot((log(AirPassengers)))
# it will male the  variance the equal 
# one with we have to make stationary with time to make variance equal using [LOG ]
# second we need to address the trend component and make the MEAN similar equal
plot(diff(log(AirPassengers)))
# this will make full stationary in mean and variance wise

# NOW we can apply time series model on it like
#airma , holw winters

#AR I MA (AR auto regressive I integration MA-moving average)
# p d q
# ar based on my past data to predict my future
# MA see different values and find average
# I to integrate of all the things
acf(AirPassengers) # vale of Q (q)
# auto corelation function
acf(diff(log(AirPassengers)))
# Determines the values of q / we have to take the value of q how- chose the  Nth line which is not crossing the BLUE LINE and select the (Nth-1) line

pacf(diff(log(AirPassengers))) # P
# Detrmins the valurs of p
# for calculatng the p Value we have to calculate the same as q value
# for D value we have to make the differentiation if we do 1st time my D value =1 and if we do differentiation twice then d=2 like that my vales will moving onnn
# lets fint our arima model
fit=arima(log(AirPassengers),c(0,1,1),seasonal = list(order=c(0,1,1),period=12))

pred <- predict(fit,n.ahead = 10*12)

ts.plot(AirPassengers,2.718^pred$pred,log="y",lty=c(1,3))

# Testing of our moel
datawide <- ts(AirPassengers,frequency = 12,start = c(1949,1),end = c(1959,12))

fit <- arima(log(datawide),c(0,1,1),seasonal = list(order=c(0,1,1),period=12))

pred <- predict(fit,n.ahead = 10*12)

pred1 <- 2.718^pred$pred

data1 <- head(pred1,12)
predicted_1960 <- round(data1,digits = 0)
original_1960 <- tail(AirPassengers,12)

ts.plot(AirPassengers ,2.718^pred$pred,log="y",lty=c(1,3))
```

